import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 375, height: 812 } });
const issues = [];
page.on('pageerror', (e) => issues.push('PAGEERROR: ' + String(e).slice(0, 120)));
await page.goto('http://localhost:8787/', { waitUntil: 'networkidle', timeout: 30000 }).catch(() => {});
await page.waitForSelector('#loader', { state: 'hidden', timeout: 20000 }).catch(() => {});
await page.waitForTimeout(2500);
await page.evaluate(() => document.querySelector('nav button[data-tab="eglence"]').click());
await page.waitForTimeout(1500);
const games = await page.evaluate(() => [...document.querySelectorAll('#tab-eglence .gbtn b')].map((b) => b.textContent));
console.log('🎪 Oyunlar:', JSON.stringify(games));
if (!games.includes('Labirent') || !games.includes('Galaksi Market')) issues.push('v6.1 kartları yok');
await page.evaluate(() => { const b = [...document.querySelectorAll('#tab-eglence .gbtn')].find((x) => x.textContent.includes('Labirent')); if (b) b.click(); });
await page.waitForTimeout(800);
const maze = await page.evaluate(() => ({ grid: !!document.getElementById('maze-grid'), cells: document.querySelectorAll('.maze-cell').length }));
console.log('🐝 Labirent grid:', maze.grid ? '✅' : '❌', '| hücre:', maze.cells);
if (!maze.grid || maze.cells === 0) issues.push('Labirent açılmıyor');
// moveBee fonksiyonunu doğrudan çağır (swipe yerine)
await page.evaluate(() => { try { moveBee(0, 1); } catch (e) { window._mazeErr = String(e); } });
await page.waitForTimeout(300);
const beePos = await page.evaluate(() => {
  const cells = [...document.querySelectorAll('.maze-cell')];
  const idx = cells.findIndex((c) => c.textContent === '🐝');
  return { idx, err: window._mazeErr || null };
});
console.log('🐝 Arı hareket:', beePos.idx >= 0 ? '✅' : '❌', beePos.err ? '| hata: ' + beePos.err : '');
await page.screenshot({ path: 'screenshots/v61-labirent.png' });
console.log(issues.length ? '🔴 SORUNLAR: ' + JSON.stringify(issues) : '✅ v6.1 HAZIR');
await browser.close();
